// ============================================================
// HSPNeighborhood — the big red button party (milestone 25)
// ------------------------------------------------------------
// Austin's ask: "add a big red button behind the bar in the
// sports bar that if you press it will start a short disco
// light show and confetti and play some music".
//
// This is the ONE definition of what a party looks like and
// how long it lasts. Imported by the client engine
// (components/NeighborhoodRoom) AND by
// /api/neighborhood/party, exactly like tomatoes.js is shared
// by the throw sim and the throw route.
//
// Same determinism trick the tomatoes use: the server
// broadcasts ONE tiny record — (id, at, durationMs) — and every
// client in the room builds the identical show from it. The
// confetti is generated by a seeded PRNG keyed on a hash of the
// party id, so two browsers hashing the same id drop the same
// hundred-odd pieces of paper in the same order without a byte
// of geometry crossing the wire. No client can publish a party:
// it rides the gameplay topic, which is server-write-only.
//
// Everything here is TRANSIENT. The show is a pure function of
// (party.at, Date.now()) — there is no accumulating state, so a
// tab whose rAF was frozen while hidden does not replay
// anything: it comes back, finds the party expired against the
// wall clock, clears one frame and is a normal sports bar
// again.
//
// Coordinates are NORMALIZED (0..1 of the overlay's width and
// height) so the same seed reads the same on a phone and on a
// desktop, and the overlay can be pinned over the whole stage
// without caring about the room camera.
//
// Nothing here touches window/document at import time; the draw
// helpers take a 2d context, so the module is safe to import in
// a serverless route.
// ============================================================

// ---- timing ------------------------------------------------

// Short on purpose: a gag, not a rave. Ten seconds is two beats
// of surprise, six of disco and two of "…and we're back".
export const PARTY_DURATION_MS = 10000;

// One press per player per this window, enforced in Postgres
// (neighborhood_record_party). The client paces itself to the
// same number so the 429 is rare.
export const PARTY_COOLDOWN_MS = 20000;

// Ramp the whole show in and out so nothing pops on or off.
const RAMP_IN_S = 0.5;
const RAMP_OUT_S = 1.8;

// How many pieces of paper. Deterministic count, so the seed
// means the same thing in every browser.
export const CONFETTI_COUNT = 132;

// ---- deterministic art -------------------------------------
// FNV-1a + mulberry32, the same pair tomatoes.js uses. Kept
// local rather than imported so this module stays a leaf.

export function seedFromId(id) {
  const str = String(id == null ? "" : id);
  let h = 2166136261 >>> 0;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 16777619) >>> 0;
  }
  return h >>> 0;
}

export function rngFrom(seed) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// ---- palettes ----------------------------------------------

const CONFETTI_COLORS = [
  "#f2c81b",
  "#e2543f",
  "#2a7de1",
  "#3fae5f",
  "#d94fb0",
  "#f28c1b",
  "#7cc4e0",
  "#f7f0dc",
];

// The gels in the lighting rig. Seven beams, seven colours, so
// the pattern never lands on itself.
const BEAM_COLORS = [
  [255, 59, 107],
  [255, 210, 59],
  [46, 230, 168],
  [59, 140, 255],
  [192, 107, 255],
  [255, 138, 59],
  [59, 230, 255],
];

const BEAM_COUNT = 7;

// ---- envelope ----------------------------------------------

// 0 at both ends, 1 in the middle. Everything (beam alpha, the
// room wash, the ball) is multiplied by this, which is why the
// show cannot leave anything behind: at elapsed >= duration the
// envelope is 0 and the overlay paints one final empty frame.
export function partyEnvelope(elapsedMs, durationMs) {
  const e = elapsedMs / 1000;
  const total = durationMs / 1000;
  if (e <= 0 || e >= total) return 0;
  const up = Math.min(1, e / RAMP_IN_S);
  const down = Math.min(1, (total - e) / RAMP_OUT_S);
  const k = Math.min(up, down);
  return k * k * (3 - 2 * k); // smoothstep
}

// ---- confetti ----------------------------------------------
//
// Two cannons go off just after the button is hit, then a
// steady fall behind them. Every piece is pure numbers: build
// once when the party starts, then position is a closed-form
// function of its age, so there is no per-frame integration to
// drift between browsers (or to blow up after a hidden tab).

const GRAVITY = 0.62; // view-heights per second squared

export function makeConfetti(seed, count) {
  const rnd = rngFrom(seed);
  const n = Math.max(0, Math.floor(count == null ? CONFETTI_COUNT : count));
  const burstN = Math.round(n * 0.44);
  const pieces = [];
  for (let i = 0; i < n; i++) {
    const burst = i < burstN;
    const side = i % 2 === 0 ? -1 : 1;
    const base = {
      color: CONFETTI_COLORS[Math.floor(rnd() * CONFETTI_COLORS.length)],
      shape: rnd() < 0.24 ? "round" : rnd() < 0.4 ? "ribbon" : "rect",
      w: 0.006 + rnd() * 0.007, // fraction of view WIDTH
      h: 0.011 + rnd() * 0.015, // fraction of view HEIGHT
      rot0: rnd() * Math.PI * 2,
      spin: (rnd() - 0.5) * 7.5,
      flipSpeed: 3.2 + rnd() * 5.5,
      phase: rnd() * Math.PI * 2,
      driftFreq: 1.1 + rnd() * 2.2,
      driftAmp: 0.012 + rnd() * 0.05,
      term: 0.3 + rnd() * 0.24, // terminal fall speed, view-heights/s
      burst,
    };
    if (burst) {
      // Cannons at the bottom corners, fired the instant the
      // dome bottoms out.
      base.birth = 0.3 + rnd() * 0.12;
      base.x0 = side < 0 ? 0.06 + rnd() * 0.05 : 0.89 + rnd() * 0.05;
      base.y0 = 1.02 + rnd() * 0.04;
      base.vx = side < 0 ? 0.16 + rnd() * 0.34 : -(0.16 + rnd() * 0.34);
      base.vy0 = -(0.95 + rnd() * 0.62); // upward
    } else {
      // The fall behind them: staggered over most of the show
      // so it is still snowing when the cannon paper lands.
      base.birth = 0.45 + rnd() * 5.4;
      base.x0 = rnd();
      base.y0 = -0.08 - rnd() * 0.45;
      base.vx = (rnd() - 0.5) * 0.055;
      base.vy0 = base.term;
    }
    pieces.push(base);
  }
  return pieces;
}

// Where one piece is at `tSec` after the party started, in
// normalized space. Returns null when it has not been fired yet
// or has fallen off the bottom.
export function confettiAt(p, tSec, fadeK) {
  const age = tSec - p.birth;
  if (age < 0) return null;

  let y;
  if (p.vy0 < p.term) {
    // Still accelerating toward terminal velocity — closed form
    // with an exact apex/terminal split, so no integration.
    const tA = (p.term - p.vy0) / GRAVITY;
    if (age <= tA) {
      y = p.y0 + p.vy0 * age + 0.5 * GRAVITY * age * age;
    } else {
      y = p.y0 + p.vy0 * tA + 0.5 * GRAVITY * tA * tA + p.term * (age - tA);
    }
  } else {
    y = p.y0 + p.term * age;
  }
  if (y > 1.14) return null;

  // Sideways: launch drift plus the flutter of a falling piece
  // of paper, easing in so a cannon shot starts straight.
  const settle = Math.min(1, age * 0.9);
  const x =
    p.x0 +
    p.vx * age * (p.burst ? Math.min(1, 1.2 / Math.max(0.35, age)) : 1) +
    Math.sin(age * p.driftFreq + p.phase) * p.driftAmp * settle;

  const alpha = Math.min(1, age * 6) * fadeK;
  if (alpha <= 0.01) return null;
  return {
    x,
    y,
    rot: p.rot0 + p.spin * age,
    // Paper turning edge-on: a squash of the short axis, never
    // fully zero so a piece never disappears mid-air.
    flip: 0.16 + 0.84 * Math.abs(Math.cos(age * p.flipSpeed + p.phase)),
    alpha,
  };
}

// One piece, already positioned in PIXELS by the caller.
export function drawConfettiPiece(ctx, p, px, py, w, h, rot, flip, alpha) {
  if (alpha <= 0) return;
  ctx.save();
  ctx.globalAlpha = alpha;
  ctx.translate(px, py);
  ctx.rotate(rot);
  ctx.scale(1, flip);
  ctx.fillStyle = p.color;
  if (p.shape === "round") {
    ctx.beginPath();
    ctx.ellipse(0, 0, w * 0.6, w * 0.6, 0, 0, Math.PI * 2);
    ctx.fill();
  } else if (p.shape === "ribbon") {
    ctx.beginPath();
    ctx.moveTo(-w * 0.5, -h * 0.7);
    ctx.quadraticCurveTo(w * 0.9, -h * 0.2, -w * 0.4, h * 0.7);
    ctx.lineWidth = Math.max(1.2, w * 0.55);
    ctx.strokeStyle = p.color;
    ctx.lineCap = "round";
    ctx.stroke();
  } else {
    ctx.fillRect(-w / 2, -h / 2, w, h);
  }
  ctx.restore();
}

// ---- the rig -----------------------------------------------

// Where the ball hangs, as a fraction of view height. It drops
// in from above the top edge and is winched back up at the end.
const BALL_REST_Y = 0.15;
const BALL_UP_Y = -0.3;
const BALL_DROP_S = 0.62;

export function ballCenterY(elapsedMs, durationMs) {
  const e = elapsedMs / 1000;
  const total = durationMs / 1000;
  const lift = RAMP_OUT_S * 0.75;
  if (e < BALL_DROP_S) {
    const u = Math.max(0, e) / BALL_DROP_S;
    // ease-out with a small settle bounce on the cable
    const k = 1 - Math.pow(1 - u, 3);
    const bounce = Math.sin(u * Math.PI) * 0.018 * (1 - u);
    return BALL_UP_Y + (BALL_REST_Y - BALL_UP_Y) * k + bounce;
  }
  if (e > total - lift) {
    const u = Math.min(1, (e - (total - lift)) / lift);
    const k = u * u;
    return BALL_REST_Y + (BALL_UP_Y - BALL_REST_Y) * k;
  }
  return BALL_REST_Y;
}

// The seven beams, in radians, at time t. They sweep as a rig
// (one rotation) with a slow counter-wobble per beam so the
// pattern breathes instead of just spinning.
export function beamAngles(tSec) {
  const out = [];
  const base = tSec * 0.82;
  for (let i = 0; i < BEAM_COUNT; i++) {
    out.push({
      a: base + (i / BEAM_COUNT) * Math.PI * 2 + Math.sin(tSec * 0.7 + i) * 0.16,
      color: BEAM_COLORS[i % BEAM_COLORS.length],
      // each beam pulses on its own phase
      pulse: 0.62 + 0.38 * (0.5 + 0.5 * Math.sin(tSec * 4.2 + i * 1.7)),
    });
  }
  return out;
}

function rgba(c, a) {
  return `rgba(${c[0]},${c[1]},${c[2]},${a.toFixed(3)})`;
}

// ---- the whole overlay -------------------------------------
//
// One call per frame, in CSS pixels of the stage. `theme` only
// decides how hard the house lights go down: a light-theme room
// needs more dimming for the beams to read.
export function drawParty(ctx, viewW, viewH, party, nowMs, theme) {
  const elapsed = nowMs - party.at;
  const dur = party.durationMs;
  const env = partyEnvelope(elapsed, dur);
  if (env <= 0) return false;
  const t = elapsed / 1000;

  const bx = viewW * 0.5;
  const by = viewH * ballCenterY(elapsed, dur);
  const ballR = Math.max(16, Math.min(viewW, viewH) * 0.055);
  const reach = Math.hypot(viewW, viewH) * 1.35;

  ctx.save();

  // House lights down, so the beams have something to be
  // brighter than.
  ctx.globalAlpha = env * (theme === "dark" ? 0.2 : 0.34);
  ctx.fillStyle = "#0a1020";
  ctx.fillRect(0, 0, viewW, viewH);
  ctx.globalAlpha = 1;

  // Beams + the pools of light they throw on the floor.
  ctx.globalCompositeOperation = "lighter";
  const beams = beamAngles(t);
  const half = 0.052;
  for (const b of beams) {
    const a = env * 0.3 * b.pulse;
    const grad = ctx.createRadialGradient(bx, by, ballR * 0.4, bx, by, reach);
    grad.addColorStop(0, rgba(b.color, a));
    grad.addColorStop(0.42, rgba(b.color, a * 0.55));
    grad.addColorStop(1, rgba(b.color, 0));
    ctx.fillStyle = grad;
    ctx.beginPath();
    ctx.moveTo(bx, by);
    ctx.lineTo(bx + Math.cos(b.a - half) * reach, by + Math.sin(b.a - half) * reach);
    ctx.lineTo(bx + Math.cos(b.a + half) * reach, by + Math.sin(b.a + half) * reach);
    ctx.closePath();
    ctx.fill();

    // where the beam crosses the floor line, a soft gobo pool
    const floorY = viewH * 0.86;
    const sin = Math.sin(b.a);
    if (sin > 0.12) {
      const d = (floorY - by) / sin;
      if (d > 0 && d < reach) {
        const gx = bx + Math.cos(b.a) * d;
        const pool = ctx.createRadialGradient(gx, floorY, 0, gx, floorY, viewW * 0.13);
        pool.addColorStop(0, rgba(b.color, env * 0.26 * b.pulse));
        pool.addColorStop(1, rgba(b.color, 0));
        ctx.fillStyle = pool;
        ctx.save();
        ctx.translate(gx, floorY);
        ctx.scale(1, 0.34);
        ctx.beginPath();
        ctx.arc(0, 0, viewW * 0.13, 0, Math.PI * 2);
        ctx.fill();
        ctx.restore();
      }
    }
  }

  // A whole-room colour wash that rolls through the gels.
  const washI = Math.floor(t * 2.1) % BEAM_COLORS.length;
  const washC = BEAM_COLORS[washI];
  ctx.fillStyle = rgba(washC, env * 0.07);
  ctx.fillRect(0, 0, viewW, viewH);
  ctx.globalCompositeOperation = "source-over";

  drawDiscoBall(ctx, bx, by, ballR, t, env);

  // Confetti last: it is the closest thing to the camera.
  const fade = Math.min(1, Math.max(0, (dur / 1000 - t) / 1.1));
  for (const p of party.confetti) {
    const at = confettiAt(p, t, fade);
    if (!at) continue;
    drawConfettiPiece(
      ctx,
      p,
      at.x * viewW,
      at.y * viewH,
      p.w * viewW,
      p.h * viewH,
      at.rot,
      at.flip,
      at.alpha
    );
  }

  ctx.restore();
  return true;
}

// A mirror ball on a short cable: facet grid, a bright side, a
// few travelling glints.
export function drawDiscoBall(ctx, x, y, r, t, env) {
  ctx.save();
  ctx.globalAlpha = Math.min(1, env * 1.6);

  // cable up out of frame
  ctx.strokeStyle = "rgba(20,26,38,0.75)";
  ctx.lineWidth = Math.max(2, r * 0.09);
  ctx.beginPath();
  ctx.moveTo(x, -40);
  ctx.lineTo(x, y - r * 0.98);
  ctx.stroke();
  // motor housing
  ctx.fillStyle = "#2a3346";
  ctx.beginPath();
  ctx.ellipse(x, y - r * 1.02, r * 0.22, r * 0.14, 0, 0, Math.PI * 2);
  ctx.fill();

  // body
  ctx.beginPath();
  ctx.arc(x, y, r, 0, Math.PI * 2);
  ctx.fillStyle = "#8d99ad";
  ctx.fill();
  ctx.strokeStyle = "rgba(18,24,36,0.55)";
  ctx.lineWidth = Math.max(1.5, r * 0.06);
  ctx.stroke();

  // facets: 7 latitude bands x 12 longitudes, lit by where the
  // facet faces relative to the spin
  ctx.save();
  ctx.beginPath();
  ctx.arc(x, y, r * 0.985, 0, Math.PI * 2);
  ctx.clip();
  const spin = t * 2.1;
  const rows = 7;
  const cols = 12;
  for (let iy = 0; iy < rows; iy++) {
    const v0 = -1 + (2 * iy) / rows;
    const v1 = -1 + (2 * (iy + 1)) / rows;
    const cy0 = y + v0 * r;
    const cy1 = y + v1 * r;
    const vm = (v0 + v1) / 2;
    const rowR = Math.sqrt(Math.max(0.02, 1 - vm * vm)) * r;
    for (let ix = 0; ix < cols; ix++) {
      const lon0 = (ix / cols) * Math.PI * 2 + spin;
      const lon1 = ((ix + 1) / cols) * Math.PI * 2 + spin;
      const cx0 = x + Math.sin(lon0) * rowR;
      const cx1 = x + Math.sin(lon1) * rowR;
      if (Math.cos((lon0 + lon1) / 2) < 0) continue; // back of the ball
      // brightness: facing the (fixed) key light up-left
      const nx = Math.sin((lon0 + lon1) / 2);
      const lit = Math.max(0, 0.55 - nx * 0.45 - vm * 0.3);
      const shade = 0.32 + lit;
      ctx.fillStyle = `rgba(${Math.round(150 + 105 * lit)},${Math.round(
        162 + 93 * lit
      )},${Math.round(180 + 75 * lit)},${shade.toFixed(3)})`;
      ctx.beginPath();
      ctx.moveTo(cx0, cy0);
      ctx.lineTo(cx1, cy0);
      ctx.lineTo(cx1, cy1);
      ctx.lineTo(cx0, cy1);
      ctx.closePath();
      ctx.fill();
    }
  }
  ctx.restore();

  // glints — little four-point stars crawling over the surface
  ctx.globalCompositeOperation = "lighter";
  for (let i = 0; i < 5; i++) {
    const a = t * (1.6 + i * 0.37) + i * 2.1;
    const gx = x + Math.cos(a) * r * (0.28 + 0.34 * ((i % 3) / 2));
    const gy = y + Math.sin(a * 0.83 + i) * r * 0.55;
    const k = 0.35 + 0.65 * Math.abs(Math.sin(t * 5.1 + i * 1.9));
    const s = r * (0.2 + 0.2 * k);
    ctx.fillStyle = `rgba(255,255,255,${(0.55 * k).toFixed(3)})`;
    ctx.beginPath();
    ctx.moveTo(gx, gy - s);
    ctx.quadraticCurveTo(gx, gy, gx + s, gy);
    ctx.quadraticCurveTo(gx, gy, gx, gy + s);
    ctx.quadraticCurveTo(gx, gy, gx - s, gy);
    ctx.quadraticCurveTo(gx, gy, gx, gy - s);
    ctx.closePath();
    ctx.fill();
  }
  ctx.restore();
}
